# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    weight: 10
  - parent: About
    name: About ReSA
    url: about
    weight: 10
  - parent: About
    name: Governance
    url: about/governance
    weight: 20
  - parent: About
    name: Our Team
    url: about/our-team
    weight: 30
  - parent: About
    name: Organisational Membership
    url: about/membership
    weight: 40
  - parent: About
    name: Stakeholders
    url: about/stakeholders
    weight: 50
  - parent: About
    name: Donate
    url: about/donate
    weight: 60
  - parent: About
    name: Contact Us
    url: about/contact
    weight: 70 
  - parent: About
    name: Code of Conduct
    url: about/code-of-conduct
    weight: 80  


  - name: Task Forces
    weight: 20
  - parent: Task Forces
    name: About Task Forces
    url: taskforces
    weight: 10
  - parent: Task Forces
    name: Task Force Support
    url: taskforces/tf-support
    weight: 20

  - name: Forums
    weight: 30
    url: forums
  - parent: Forums
    name: Research Software Funders Forum
    url: forums/funders-forum
    weight: 10
  - parent: Forums
    name: Research Software Infrastructure Forum
    url: forums/rsi-forum
    weight: 20
  - parent: Forums
    name: Research Software Policy Forum
    url: forums/rsp-forum
    weight: 30  
  - parent: Forums
    name: Metascience and Research Software Forum
    url: forums/mars-forum
    weight: 40
  - parent: Forums
    name: Publishing Research Software Forum
    url: forums/pubsoft-forum
    weight: 50
  - parent: Forums
    name: Skills and Training for Research Software Forum
    url: forums/stars-forum
    weight: 60
  - parent: Forums
    name: ADORE.software Secretariat
    url: https://adore.software
    weight: 70
  - parent: Forums
    name: International Council of RSE Associations
    url: https://researchsoftware.org/council.html
    weight: 80
  - parent: Forums
    name: Community Leaders Forum
    url: forums/community-forum
    weight: 90

  - name: Resources
    weight: 40
    url: resources_page
  - parent: Resources
    name: ReSA Resources
    url: resources_page/resa-resources
    weight: 10
  - parent: Resources
    name: Guidelines
    url: resources_page/guidelines
    weight: 20
  - parent: Resources
    name: Funding Opportunities
    url: resources_page/funding-opportunities
    weight: 30
  - parent: Resources
    name: Software Policies
    url: resources_page/software-policies
    weight: 40
  - parent: Resources
    name: ADORE.software Declaration
    url: https://adore.software
    weight: 50
  - parent: Resources
    name: Research Software Engineers (RSEs)
    url: resources_page/research-software-engineers
    weight: 60

  - name: News
    url: news
    weight: 50
  - name: Events
    url: events
    weight: 60
  - parent: Events
    name: ReSA Events
    url: events/resa-events
    weight: 10
  - parent: Events
    name: ReSA Community Calls
    url: events/community-calls
    weight: 20 
  - name: Blog
    url: blog
    weight: 70
  - name: "<i class='fab fa-github'></i>"
    url: https://github.com/researchsoft/website
    weight: 80
  - name: "<i class='fas fa-envelope'></i>"
    url: mailto:contact@researchsoft.org
    weight: 90
  - name: "<i class='fab fa-slack'></i>"
    url: https://researchsoft.slack.com/
    weight: 100
  - name: "<i class='fab fa-linkedin'></i>"
    url: https://www.linkedin.com/company/research-software-alliance/
    weight: 110
  - name: "<i class='fab fa-mastodon'></i>"
    url: https://fosstodon.org/@researchsoft
    weight: 120
  - name: "<i class='fas fa-rss'></i>"
    url: /index.xml
    weight: 130
