baseURL = "https://researchsoft.org"
# Google Analytics tracking
googleAnalytics = "UA-181241343-1"

languageCode = "en-uk"
LanguageCode = "en-uk"
title = "Research Software Alliance"
theme = 'ananke'
enableGitInfo = true
version = "0.17.3"
rssLimit = 100

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputs]
  home = ["ATOM", "HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName  = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  github = "https://github.com/researchsoft"
  site_logo = "img/resa-logo-software-green.png"
  name = "The Research Software Alliance"
  customCSS = ["css/custom.css"]

  date_format = "January 2, 2006"
  dateFormatAtomFeed = "2006-01-02T15:04:05-07:00"
  dateFormatTag = "2006"
  feedUUID = "283aaa54-faf6-4bcd-9cb8-74a13b96063c"
  # icon = ""
  # icon96 = ""
  # logo = "img/resa-logo-software-green.png"
  mainSections = ["blog"]

  [params.colors]
    primary = "darkgreen"
    secondary = "darkorange"

[menus]
  [[menus.main]]
    name = 'About'
    url = '/about-resa/'
    weight = 10
  [[menus.main]]
    name = 'About RESA'
    url = '/about-resa/about-resa'
    parent = 'About'
    weight = 11
  [[menus.main]]
    name = 'Governance'
    url = '/about-resa/governance'
    parent = 'About'
    weight = 12
  [[menus.main]]
    name = 'People'
    url = '/about-resa/people'
    parent = 'About'
    weight = 13
  [[menus.main]]
    name = 'Organisational Membership'
    url = '/about-resa/membership'
    parent = 'About'
    weight = 14
  [[menus.main]]
    name = 'Donate'
    url = '/about-resa/donate'
    parent = 'About'
    weight = 15
  [[menus.main]]
    name = 'Task Forces'
    url = '/taskforces/'
    weight = 20
  [[menus.main]]
    name = 'About Task Forces'
    url = '/taskforces/about-taskforces'
    parent = 'Task Forces'
    weight = 21
  [[menus.main]]
    name = 'Task Force Support'
    url = '/taskforces/tf-support'
    parent = 'Task Forces'
    weight = 22
  [[menus.main]]
    name = 'Forums'
    url = '/forums/'
    weight = 30
  [[menus.main]]
    name = 'Funders Forum'
    url = '/forums/funders-forum'
    parent = 'Forums'
    weight = 31
  [[menus.main]]
    name = 'Research Software Infrastructure Forum'
    url = '/forums/rsi-forum'
    parent = 'Forums'
    weight = 32
  [[menus.main]]
    name = 'ADORE.software Secretariat'
    url = 'https://adore.software/'
    parent = 'Forums'
    weight = 33
  [[menus.main]]
    name = 'International Council of RSE Associations'
    url = 'https://researchsoftware.org/council.html'
    parent = 'Forums'
    weight = 34
  [[menus.main]]
    name = 'Community Leaders Forum'
    url = '/forums/community-forum'
    parent = 'Forums'
    weight = 35

  [[menus.main]]
    name = 'Resources'
    url = '/resa-resources/'
    weight = 40
  [[menus.main]]
    name = 'Guidelines'
    url = '/resa-resources/guidelines'
    parent = 'Resources'
    weight = 42
  [[menus.main]]
    name = 'Funding Opportunities'
    url = '/resa-resources/funding-opportunities'
    parent = 'Resources'
    weight = 43
  [[menus.main]]
    name = 'Software Policies'
    url = '/resa-resources/software-policies'
    parent = 'Resources'
    weight = 44
  [[menus.main]]
    name = 'ADORE.software Declaration'
    url = 'https://adore.software/'
    parent = 'Resources'
    weight = 45
  [[menus.main]]
    name = 'Research Software Engineers (RSEs)'
    url = '/resa-resources/research-software-engineers'
    parent = 'Resources'
    weight = 46

  [[menus.main]]
    name = 'News'
    url = '/news/'
    weight = 50
  [[menus.main]]
    name = 'Events'
    url = '/events/'
    weight = 60
  [[menus.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 70
[[menus.footer_social]]
  name = "github"
  url = "https://github.com/researchsoft/website"
  weight = 30
  pre = "fab fa-github fa-stack-2x"
[[menus.footer_social]]
  name = "email"
  pageRef = "contact/"
  weight = 40
  pre = "fa fa-envelope"
[[menus.footer_social]]
  name = "slack"
  url = "https://join.slack.com/t/researchsoft/shared_invite/zt-1flmrglww-SoWjAK_5TJyqLU_~Jx697w"
  weight = 50
  pre = "fab fa-slack"
[[menus.footer_social]]
  name = "Mastodon"
  url = "https://fosstodon.org/@researchsoft"
  weight = 60
  pre = "fab fa-mastodon"
[[menus.footer_social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/research-software-alliance"
  weight = 60
  pre = "fab fa-linkedin"  
[[menus.footer_social]]
  name = "Atom Feed"
  pageRef = "feed.xml"
  weight = 70
  pre = "fa fa-rss"
[[menus.copyright_footer]]
  name = "License"
  pageRef = "license"
  weight = 60
  color = "primary"
[[menus.copyright_footer]]
  name = "Code of Conduct"
  pageRef = "code-of-conduct"
  weight = 70
  color = "primary"

[author]
  name = "Research Software Alliance"
