baseURL = "https://researchsoft.org"
# Google Analytics tracking
googleAnalytics = "UA-181241343-1"

languageCode = "en-uk"
LanguageCode = "en-uk"
title = "Research Software Alliance"
theme = 'ananke'
enableGitInfo = true
version = "0.17.3"
rssLimit = 100


[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputs]
  home = ["ATOM", "HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName  = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  github = "https://github.com/researchsoft"
  site_logo = "img/resa-logo-software-green.png"
  name = "The Research Software Alliance"
  customCSS = ["css/custom.css"]

  date_format = "January 2, 2006"
  dateFormatAtomFeed = "2006-01-02T15:04:05-07:00"
  dateFormatTag = "2006"
  feedUUID = "283aaa54-faf6-4bcd-9cb8-74a13b96063c"
  # icon = ""
  # icon96 = ""
  # logo = "img/resa-logo-software-green.png"
  mainSections = ["blog"]
  buildFuture = true


  [params.colors]
    primary = "darkgreen"
    secondary = "darkorange"

[menus]
 [[menus.footer_social]]
  name = "github"
  url = "https://github.com/researchsoft/website"
  weight = 30
  pre = "fab fa-github fa-stack-2x"
[[menus.footer_social]]
  name = "email"
  pageRef = "contact/"
  weight = 40
  pre = "fa fa-envelope"
[[menus.footer_social]]
  name = "slack"
  url = "https://join.slack.com/t/researchsoft/shared_invite/zt-1flmrglww-SoWjAK_5TJyqLU_~Jx697w"
  weight = 50
  pre = "fab fa-slack"
[[menus.footer_social]]
  name = "Mastodon"
  url = "https://fosstodon.org/@researchsoft"
  weight = 60
  pre = "fab fa-mastodon"
[[menus.footer_social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/research-software-alliance"
  weight = 60
  pre = "fab fa-linkedin"  
[[menus.footer_social]]
  name = "Atom Feed"
  pageRef = "feed.xml"
  weight = 70
  pre = "fa fa-rss"
[[menus.copyright_footer]]
  name = "License"
  pageRef = "license"
  weight = 60
  color = "primary"
[[menus.copyright_footer]]
  name = "Code of Conduct"
  pageRef = "code-of-conduct"
  weight = 70
  color = "primary"

[author]
  name = "Research Software Alliance"
