[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.135.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/about-resa"
  to = "/about"
  status = 301
[[redirects]]
  from = "/about-resa/"
  to = "/about"
  status = 301
[[redirects]]
  from = "/governance"
  to = "/about/governance"
  status = 301
[[redirects]]
  from = "/our-team"
  to = "/about/our-team"
  status = 301
[[redirects]]
  from = "/membership"
  to = "/about/membership"
  status = 301
[[redirects]]
  from = "/stakeholders"
  to = "/about/stakeholders"
  status = 301
[[redirects]]
  from = "/donate"
  to = "/about/donate"
  status = 301
[[redirects]]
  from = "/contact/"
  to = "/about/contact"
  status = 301
[[redirects]]
  from = "/code-of-conduct"
  to = "/about/code-of-conduct"
  status = 301

[[redirects]]
  from = "/taskforces"
  to = "/taskforces"
  status = 301
[[redirects]]
  from = "/taskforces/"
  to = "/taskforces"
  status = 301
[[redirects]]
  from = "/tf-support"
  to = "/taskforces/tf-support"
  status = 301

[[redirects]]
  from = "/forums"
  to = "/forums"
  status = 301
[[redirects]]
  from = "/forums/"
  to = "/forums"
  status = 301
[[redirects]]
  from = "/community-leadership-forum"
  to = "/forums/community-leadership-forum"
  status = 301
[[redirects]]
  from = "/funders-forum"
  to = "/forums/funders-forum"
  status = 301
[[redirects]]
  from = "/rsi-forum"
  to = "/forums/rsi-forum"
  status = 301
[[redirects]]
  from = "/rsp-forum"
  to = "/forums/rsp-forum"
  status = 301
[[redirects]]
  from = "/mars-forum"
  to = "/forums/mars-forum"
  status = 301
[[redirects]]
  from = "/pubsoft-forum"
  to = "/forums/pubsoft-forum"
  status = 301
[[redirects]]
  from = "/stars-forum"
  to = "/forums/stars-forum"
  status = 301
[[redirects]]
  from = "/adore.software/"
  to = "https://adore.software"
  status = 301
[[redirects]]
  from = "/council.html"
  to = "https://researchsoftware.org/council.html"
  status = 301

[[redirects]]
  from = "/resa-resources"
  to = "/resource"
  status = 301
[[redirects]]
  from = "/resa-resources/"
  to = "/resource"
  status = 301
[[redirects]]
  from = "/guidelines"
  to = "/resource/guidelines"
  status = 301
[[redirects]]
  from = "/funding-opportunities"
  to = "/resource/funding-opportunities"
  status = 301
[[redirects]]
  from = "/software-policies"
  to = "/resource/software-policies"
  status = 301
[[redirects]]
  from = "/research-software-engineers"
  to = "/resource/research-software-engineers"
  status = 301
[[redirects]]
  from = "/adore.software/"
  to = "https://adore.software"
  status = 301

[[redirects]]
  from = "/news"
  to = "/news"
  status = 301
[[redirects]]
  from = "/events"
  to = "/events"
  status = 301
[[redirects]]
  from = "/events/"
  to = "/events"
  status = 301
[[redirects]]
  from = "/community-calls"
  to = "/events/community-calls"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog"
  status = 301
[[redirects]]
  from = "/feed.xml"
  to = "/index.xml"
  status = 301

[[redirects]]
  from = "/events/events/2021-12"
  to = "/events/events-past/2021-12>"
  status = 301 

[[redirects]]
  from = "/events/events/2022-04"
  to = "/events/events-past/2022-04>"
  status = 301 

[[redirects]]
  from = "/events/events/2022-05"
  to = "/events/events-past/2022-05>"
  status = 301

[[redirects]]
  from = "/events/events/2022-06"
  to = "/events/events-past/2022-06>"
  status = 301

[[redirects]]
  from = "/events/events/2024-01"
  to = "/events/events-past/2024-01>"
  status = 301

[[redirects]]
  from = "/events/events/2024-10"
  to = "/events/events-past/2024-10>"
  status = 301

[[redirects]]
  from = "/events/events/2025-02"
  to = "/events/events-past/2025-02>"
  status = 301

[[redirects]]
  from = "/events/events/2025-03"
  to = "/events/events-past/2025-03>"
  status = 301
  