[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
    HUGO_VERSION = "latest"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "latest"

[context.deploy-preview.environment]
  HUGO_VERSION = "latest"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
